use_frameworks!

platform :ios, '8.0'

target 'RN_MyProfile_Example' do
  pod 'RN_MyProfile', :path => '../'

  target 'RN_MyProfile_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
